# browsers key accepts all keys, as mozwebqa:
# https://github.com/davehunt/pytest-mozwebqa#running-tests-with-pytest_mozwebqa
# but please keep it only browser related
browsers: []
    # - browsername: chrome

# basic setting for each run (py.test call parameters)
run:
    baseurl: http://localhost:9090
    skipurlcheck: true
    #k: test_module_name

# this sets the test type (selenium or saucelabs)
type: selenium
testpath: ./    # basepath to run tests in
selenium:
    xvfb:
        xvfb_on: true
        # xvfb settings for xvfb mode (consult man xfvb-run here)
        # However if xvfb_on is set to false, will not run in xvfb mode at all
        options:
            server-args: -screen 0 1024x768x24
            auto-servernum: true
    chromedriver:
        file: ./chromedriver # chromedriver location
        url: http://chromedriver.storage.googleapis.com/2.8/  # chromedriver repository
        zips: # filenames
            win: chromedriver_win32.zip
            mac: chromedriver_mac32.zip
            linux32: chromedriver_linux32.zip
            linux64: chromedriver_linux64.zip

saucelabs:
    connect: # saucelabs connect and download url
        file: ./Saucelabs-Connect-latest.jar
        url: https://saucelabs.com/downloads/Sauce-Connect-latest.zip
